on:
  push:
  schedule:
    - cron: "0 17 * * *"
name: Mirror GitHub Auto Queried Repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/leanflutter
          dst: gitee/leanflutter
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          # force_update: true
